<div class="home_main">
    <div class="home_core_head"><h1>ITCS</h1></div>
    <div class="home_core_image_big"></div>
    <div class="home_core_content">
        <div class="content_home">
            
        </div>
        <?php include 'menu_all.php'; ?>
    </div>
    
    <div class="home_core_head_all"><h1>Core Consulting</h1></div>
    <div class="home_core_image_big_all"></div>
    <div class="home_core_content_all"><p>There have had been invasions by strong kings and dictators to achieve goals through diplomacy, alliances & establishing relationships between kingdoms through marriages! A similar situation can be observed in the modern day business world.<br>
            Traditional consulting firms have been great contributors to modern management. Their powerful ideas and immense subject knowledge have solved business problems in a legendary manner and also driven up the worth of consultants across the business world. Consultants are generally regarded as expensive. Some agree to the fact that their ideas and solutions are of real help but those who don't think so, regard them as overrated professionals. After the recession, most businesses are looking for consulting firms that can provide an end-to-end solution to their problems.<br>
            No more do they want consultants that would woo them with their analysis and models. Instead, they wanted a one-stop solution to their problem, meaning consulting firms who could identify, strategize, implement their strategies and make them operational. Moreover, there has been a perpetual reluctance among business houses on the disclosure of information front. Businesses want secrecy of their information, which is why they are reluctant to hire many outsiders. Added to that is the problem of price for consulting services, which is generally very high. Cost cutting firms thus wanted quality consulting services at cheaper prices. We at ValeurHR identify these problems and work on the nature of the issues through our expert consultation to buyout the advantage of creating long term relationships with clients. We have always been acknowledged as a trusted partner as we realize that we could provide bundled consulting services to the clients at best prices. Combining each of the consulting elements, we embark on the journey towards the "valley of the brains" which essentially means intruding into the arena that the traditional heavyweight problems had been controlling.
        </p>
    </div>
    
    <div class="home_core_head"><h1>Masters of Value Consulting</h1></div>
    <div class="home_core_image_big"><img src="images/cor2.jpg" width="100%"/></div>
    <div class="home_core_content"><p>Consulting has always been a valuable profession to go for a lot of people for different reasons like career, opportunities, networking and even the skills involved. ITCS has been constantly striving to put its partners and clients in the right direction of the purpose of Consulting. Though consulting has been going on for ages in one or the other form, we at ValeurHR see it as innovative value adding factor which is designed in a way that it takes very good care of the pain areas of the client. It has to be really inspiring to work in a setup of consulting from each member involved. We follow principle of “More from Less for More” (MLM) substantiate consulting being one of the most value adding professions across the globe. The principle states that innovation should be such that more value can be generated from less resource for more people, which indeed deserve a deep thought analysis over the existence of profession of consulting management.<br>
            In its real essence, management is a business of value creation where each discipline is practiced for creating something worthy out of nothing for sustainable development. What is value? Is it just the multiplier of money? It is necessarily not! It is sustainability which must follow the rule of 3Ps, where value needs to be created for People at an individual level, Profit at organizational level and Planet at societal level. All the disciplines of management focus on creating value for the existing and non-existing propositions in a comprehensive and inclusive manner which has become more important now after the subprime crisis of 2008, where the whole myth of extensive value was a mere bubble that eventually busted out leaving the world in the lurch of crisis. To prevent such cases, there is a strict need for inclusiveness over diversity where it is not just about counting the numbers but making those numbers count with accountability to create value for the larger sustainable benefit. Therefore, it would not be an exaggeration to say that consulting is a profession which initiates the foreplay to create synergies among all other noble professions.<br>
            We at ITCS strive to keep the organization and members on the front foot to keep the real purpose of consulting profession hale and hearty by aligning with the right businesses and resources.
        </p>
    </div>
</div>